#!/bin/bash
#获取公网IP
get_ip(){
    local IP=$( ip addr | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v "^192\.168|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-2]\.|^10\.|^127\.|^255\.|^0\." | head -n 1 )
    [ -z ${IP} ] && IP=$( wget -qO- -t1 -T2 ipv4.icanhazip.com )
    [ -z ${IP} ] && IP=$( wget -qO- -t1 -T2 ipinfo.io/ip )
    [ ! -z ${IP} ] && echo ${IP} || echo
}
systemctl stop firewalld
systemctl disable firewalld
setenforce 0
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
yum -y install wget
yum -y install vim
yum -y install lsof
yum -y install iptables*
yum -y install epel-release
systemctl stop iptables
#iptables -F
cp /etc/sysconfig/iptables /etc/sysconfig/iptables.$(date +%Y%m%d-%H%M%S).bak
ip=`get_ip`
cat > /etc/sysconfig/iptables <<EOF
# Generated by iptables-save v1.4.21 on Thu May 17 21:07:44 2018
*mangle
:PREROUTING ACCEPT [5:260]
:INPUT ACCEPT [5:260]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [12:1640]
:POSTROUTING ACCEPT [12:1640]
COMMIT
# Completed on Thu May 17 21:07:44 2018
# Generated by iptables-save v1.4.21 on Thu May 17 21:07:44 2018
*nat
:PREROUTING ACCEPT [2:104]
:INPUT ACCEPT [2:104]
:OUTPUT ACCEPT [1:76]
:POSTROUTING ACCEPT [1:76]
COMMIT
# Completed on Thu May 17 21:07:44 2018
# Generated by iptables-save v1.4.21 on Thu May 17 21:07:44 2018
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT DROP [0:0]
-A INPUT -s 123.59.194.60 -p tcp -m multiport --dports 22 -j ACCEPT
-A INPUT -d $ip -p tcp -m multiport --sports 22 -j ACCEPT
-A INPUT -p udp -m multiport --dports 25,53,161 -j ACCEPT
-A INPUT -p udp -m multiport --sports 25,53,161 -j ACCEPT
-A INPUT -p tcp -m multiport --dports 25,80,88,443,666,888,873,8888,9000,10050,10051 -j ACCEPT
-A INPUT -p tcp -m multiport --sports 25,80,88,443,666,888,873,8888,9000,10050,10051 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A OUTPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p udp -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -p icmp -j ACCEPT
COMMIT
# Completed on Thu May 17 21:07:44 2018
EOF

#systemctl restart iptables
#systemctl enable iptables
echo -e '''\033[31m请检查iptables无误后，重启防火墙，并运行"systemctl enable iptables" 